name: docker build
on:
  release:
    types:
      - published
jobs:
  push_to_ghcr_io:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${{ github.event.release.tag_name }}
      - name: Set current date as env variable
        id: date_time
        run: echo ::set-output name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: build&push live
        if: ${{ github.event.release.target_commitish == 'live' }}
        run: |
            docker build docker/ --build-arg TP_RELEASE=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE=${{ steps.date_time.outputs.NOW }} --tag ghcr.io/gilbn/theme.park --tag ghcr.io/gilbn/theme.park:${{ steps.get_version.outputs.VERSION }}
            docker push ghcr.io/gilbn/theme.park
      - name: build&push dev
        if: ${{ github.event.release.target_commitish == 'live_develop' }}
        run: |
            docker build docker/ --build-arg TP_RELEASE=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE=${{ steps.date_time.outputs.NOW }} --tag ghcr.io/gilbn/theme.park:develop --tag ghcr.io/gilbn/theme.park:${{ steps.get_version.outputs.VERSION }}
            docker push --all-tags ghcr.io/gilbn/theme.park
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${{ github.event.release.tag_name }}
      - name: Set current date as env variable
        id: date_time
        run: echo ::set-output name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build&push dh live
        if: ${{ github.event.release.target_commitish == 'live' }}
        run: |
            docker build docker/ --build-arg TP_RELEASE=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE=${{ steps.date_time.outputs.NOW }} --tag ghcr.io/gilbn/theme.park --tag ghcr.io/gilbn/theme.park:${{ steps.get_version.outputs.VERSION }}
            docker push ghcr.io/gilbn/theme.park
      - name: build&push dh dev
        if: ${{ github.event.release.target_commitish == 'live_develop' }}
        run: |
            docker build docker/ --build-arg TP_RELEASE=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE=${{ steps.date_time.outputs.NOW }} --tag gilbn/theme.park:develop --tag gilbn/theme.park:${{ steps.get_version.outputs.VERSION }}
            docker push --all-tags gilbn/theme.park

